/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as ApiAiGenerateMenuRouteImport } from './routes/api/ai/generate-menu'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardOrdersRouteImport } from './routes/_authenticated/dashboard.orders'
import { Route as AuthenticatedDashboardMenuRouteImport } from './routes/_authenticated/dashboard.menu'
import { Route as AuthenticatedDashboardIntegrationsRouteImport } from './routes/_authenticated/dashboard.integrations'
import { Route as AuthenticatedDashboardAiToolsRouteImport } from './routes/_authenticated/dashboard.ai-tools'
import { Route as AuthenticatedAdminTablesRouteImport } from './routes/_authenticated/admin.tables'
import { Route as ApiPublicWebhookPlatformRouteImport } from './routes/api/public/webhook.$platform'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiAiGenerateMenuRoute = ApiAiGenerateMenuRouteImport.update({
  id: '/api/ai/generate-menu',
  path: '/api/ai/generate-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrdersRoute =
  AuthenticatedDashboardOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMenuRoute =
  AuthenticatedDashboardMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIntegrationsRoute =
  AuthenticatedDashboardIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAiToolsRoute =
  AuthenticatedDashboardAiToolsRouteImport.update({
    id: '/ai-tools',
    path: '/ai-tools',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminTablesRoute =
  AuthenticatedAdminTablesRouteImport.update({
    id: '/admin/tables',
    path: '/admin/tables',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicWebhookPlatformRoute =
  ApiPublicWebhookPlatformRouteImport.update({
    id: '/api/public/webhook/$platform',
    path: '/api/public/webhook/$platform',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/m/$slug': typeof MSlugRoute
  '/admin/tables': typeof AuthenticatedAdminTablesRoute
  '/dashboard/ai-tools': typeof AuthenticatedDashboardAiToolsRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/menu': typeof AuthenticatedDashboardMenuRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/api/ai/generate-menu': typeof ApiAiGenerateMenuRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/webhook/$platform': typeof ApiPublicWebhookPlatformRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/m/$slug': typeof MSlugRoute
  '/admin/tables': typeof AuthenticatedAdminTablesRoute
  '/dashboard/ai-tools': typeof AuthenticatedDashboardAiToolsRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/menu': typeof AuthenticatedDashboardMenuRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/api/ai/generate-menu': typeof ApiAiGenerateMenuRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/api/public/webhook/$platform': typeof ApiPublicWebhookPlatformRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/m/$slug': typeof MSlugRoute
  '/_authenticated/admin/tables': typeof AuthenticatedAdminTablesRoute
  '/_authenticated/dashboard/ai-tools': typeof AuthenticatedDashboardAiToolsRoute
  '/_authenticated/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/_authenticated/dashboard/menu': typeof AuthenticatedDashboardMenuRoute
  '/_authenticated/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/api/ai/generate-menu': typeof ApiAiGenerateMenuRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/webhook/$platform': typeof ApiPublicWebhookPlatformRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/m/$slug'
    | '/admin/tables'
    | '/dashboard/ai-tools'
    | '/dashboard/integrations'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/api/ai/generate-menu'
    | '/dashboard/'
    | '/api/public/webhook/$platform'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/m/$slug'
    | '/admin/tables'
    | '/dashboard/ai-tools'
    | '/dashboard/integrations'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/api/ai/generate-menu'
    | '/dashboard'
    | '/api/public/webhook/$platform'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/m/$slug'
    | '/_authenticated/admin/tables'
    | '/_authenticated/dashboard/ai-tools'
    | '/_authenticated/dashboard/integrations'
    | '/_authenticated/dashboard/menu'
    | '/_authenticated/dashboard/orders'
    | '/_authenticated/dashboard/profile'
    | '/api/ai/generate-menu'
    | '/_authenticated/dashboard/'
    | '/api/public/webhook/$platform'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  MSlugRoute: typeof MSlugRoute
  ApiAiGenerateMenuRoute: typeof ApiAiGenerateMenuRoute
  ApiPublicWebhookPlatformRoute: typeof ApiPublicWebhookPlatformRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/ai/generate-menu': {
      id: '/api/ai/generate-menu'
      path: '/api/ai/generate-menu'
      fullPath: '/api/ai/generate-menu'
      preLoaderRoute: typeof ApiAiGenerateMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/orders': {
      id: '/_authenticated/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/menu': {
      id: '/_authenticated/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof AuthenticatedDashboardMenuRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/integrations': {
      id: '/_authenticated/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/ai-tools': {
      id: '/_authenticated/dashboard/ai-tools'
      path: '/ai-tools'
      fullPath: '/dashboard/ai-tools'
      preLoaderRoute: typeof AuthenticatedDashboardAiToolsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/tables': {
      id: '/_authenticated/admin/tables'
      path: '/admin/tables'
      fullPath: '/admin/tables'
      preLoaderRoute: typeof AuthenticatedAdminTablesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/webhook/$platform': {
      id: '/api/public/webhook/$platform'
      path: '/api/public/webhook/$platform'
      fullPath: '/api/public/webhook/$platform'
      preLoaderRoute: typeof ApiPublicWebhookPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAiToolsRoute: typeof AuthenticatedDashboardAiToolsRoute
  AuthenticatedDashboardIntegrationsRoute: typeof AuthenticatedDashboardIntegrationsRoute
  AuthenticatedDashboardMenuRoute: typeof AuthenticatedDashboardMenuRoute
  AuthenticatedDashboardOrdersRoute: typeof AuthenticatedDashboardOrdersRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAiToolsRoute: AuthenticatedDashboardAiToolsRoute,
    AuthenticatedDashboardIntegrationsRoute:
      AuthenticatedDashboardIntegrationsRoute,
    AuthenticatedDashboardMenuRoute: AuthenticatedDashboardMenuRoute,
    AuthenticatedDashboardOrdersRoute: AuthenticatedDashboardOrdersRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedAdminTablesRoute: typeof AuthenticatedAdminTablesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedAdminTablesRoute: AuthenticatedAdminTablesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  MSlugRoute: MSlugRoute,
  ApiAiGenerateMenuRoute: ApiAiGenerateMenuRoute,
  ApiPublicWebhookPlatformRoute: ApiPublicWebhookPlatformRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
